paper:
  learning_rate: 0.001
  dropout_rate: 0.5
  hidden_nums: 700
  batch_size: 32
  kernel_size: 3
  filter_nums: 50
  C_tar: 5
  C_sent: 7
  beta: 1.0
  gamma: 0.7

custom:
  learning_rate: 0.001
  dropout_rate: 0.0
  hidden_nums: 700
  batch_size: 32
  kernel_size: 3
  filter_nums: 50
  C_tar: 3
  C_sent: 7
  beta: 1.0
  gamma: 0.7
